Repository Seneca-CDOT/plumadriver, pull requests merged in 2020-01, with the labels that each got.

#115 test: add session tests
  test/jest/e2e/session.test.js
Labels: Type: Enhancement

#122 refactor: remove unnecessary NODE_ENV assignment
  src/index.ts
Labels: Priority: Medium, Type: Refactor/Cleanup

#120 feat: get page source endpoint
  src/Browser/Browser.ts
  src/Session/Session.ts
  src/constants/constants.ts
  src/routes/index.ts
  test/jest/e2e/get-page-source.test.js
Labels: Priority: High, Type: Enhancement

#121 feat: shutdown endpoint
  src/routes/index.ts
  test/jest/e2e/shutdown.test.js
Labels: Priority: High, Type: Enhancement

#124 feat: add commitizen package, configs, and scripts
  commitlint.config.js
  package-lock.json
  package.json
Labels: Priority: Medium, Type: Enhancement, dependencies

#125 fix: error in lintstaged config affecting markdown files
  .lintstagedrc.json
Labels: Priority: Medium, Type: Bug

#126 fix: correct npm lint scripts
  .eslintignore
  package.json
Labels: Priority: Medium, Type: Bug

#127 refactor: remove unnecessary constant variable in bin.js
  bin.js
Labels: Priority: Medium, Type: Refactor/Cleanup

#129 docs: update readme instructions and content
  README.md
Labels: Priority: High, Type: Enhancement

#130 docs: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Priority: High, Type: Enhancement

#132 fix: correct returning newlines in execute script sync
  src/Session/Session.ts
  test/jest/e2e/execute-script-sync.test.js
Labels: Priority: Critical, Type: Bug

#134 chore(version): update package.json to v0.6.0
  package-lock.json
  package.json
Labels: Type: Enhancement

#135 chore: convert Mocha tests to Jest
  package-lock.json
  package.json
  test/1_unit_tests/2_WebElement/webElement.js
  test/1_unit_tests/3_Browser/browser.js
  test/1_unit_tests/4_Session/session.js
  test/1_unit_tests/5_SessionManager_Tests/SessionManager.js
  test/2_endpoints_tests/1_createSession/createSession.js
  test/2_endpoints_tests/2_timeouts/timeouts.js
  test/2_endpoints_tests/3_navigation/navigation.js
  test/2_endpoints_tests/4_alerts/alerts.js
  test/2_endpoints_tests/5_cookies/cookies.js
  test/2_endpoints_tests/6_elements/elements.js
  test/2_endpoints_tests/7_script/script.js
  test/index.js
  test/jest/capability-validator.test.js
  test/test_utils.js
  test_docs/index.html
  test_docs/style.css
Labels: Type: Refactor/Cleanup

#136 docs: add missing commit types
  CONTRIBUTING.md
Labels: Type: Documentation

#137 Closes #99. Add Continuous Integration
  .circleci/config.yml
  package.json
  test/jest/e2e/navigation.test.js
  test/jest/e2e/session.test.js
  test/jest/e2e/timeouts.test.js
Labels: Priority: High, Type: Enhancement

#138 chore: update jsdom
  package-lock.json
  package.json
  src/Session/Session.ts
Labels: Priority: Medium, Type: Enhancement

#140 test: add e2e for cookie endpoints
  .eslintignore
  src/Session/Session.ts
  test/jest/Browser/Browser.test.js
  test/jest/CookieValidator.test.js
  test/jest/delete-cookie.test.js
  test/jest/e2e/cookies.test.js
  test/jest/get-named-cookie.test.js
Labels: Priority: Medium, Type: Enhancement

#141 docs: add PlumaDriver options
  README.md
Labels: Type: Documentation

#144 ci: add CircleCI for windows
  .circleci/config.yml
Labels: Priority: Low, Type: Enhancement

#145 docs: fix formatting and remove note in intro
  README.md
Labels: Priority: Medium, Type: Documentation

#146 chore: update project dependencies
  package-lock.json
  package.json
Labels: Priority: High, Type: Enhancement

#147 feat: add injector for missing jsdom apis
  src/Browser/BrowserConfig.ts
  test/jest/e2e/inject-api.test.js
Labels: Priority: High, Type: Enhancement

#148 chore(version): update to v0.7.0
  package-lock.json
  package.json
Labels: Priority: High
