Repository Seneca-CDOT/plumadriver, pull requests merged in 2020-09, with the labels that each got.

#193 chore: disable CircleCI windows build
  .circleci/config.yml
Labels: Priority: High

#191 feat: Is Element Selected endpoint
  README.md
  src/Session/Session.ts
  src/WebElement/WebElement.ts
  src/constants/constants.ts
  src/routes/elements.ts
  test/jest/element-selected.test.js
Labels: Priority: Medium

#194 Fix vulnerabilities
  package-lock.json
  package.json
Labels: Priority: High, dependencies

#197 chore: update typescript
  package-lock.json
  package.json
  src/Browser/Browser.ts
  src/Session/Session.ts
  src/Types/types.d.ts
Labels: Priority: High

#196 refactor: enable some strict options, add type for jsdom/express
  .eslintrc.json
  package-lock.json
  package.json
  src/Browser/Browser.ts
  src/Browser/BrowserConfig.ts
  src/Session/Session.ts
  src/Types/types.d.ts
  src/constants/constants.ts
  tsconfig.json
Labels: Priority: High, Type: Refactor/Cleanup

#198 refactor: enable strictNullChecks
  src/Browser/Browser.ts
  src/Browser/CookieValidator.ts
  src/Session/Session.ts
  src/Types/types.d.ts
  src/WebElement/WebElement.ts
  src/routes/cookies.ts
  src/routes/elements.ts
  src/routes/index.ts
  src/routes/timeouts.ts
  tsconfig.json
Labels: Type: Refactor/Cleanup

#200 refactor: enable strictPropertyInitialization
  src/Browser/Browser.ts
  src/Browser/BrowserConfig.ts
  src/Error/WebDriverError.ts
  src/Session/Session.ts
  tsconfig.json
Labels: Priority: High, Type: Refactor/Cleanup
