Repository Seneca-CDOT/plumadriver, pull requests merged in 2020-10, with the labels that each got.

#201 CI: Use github actions
  .github/workflows/run_tests.yml
Labels: Priority: Low, Type: Enhancement

#205 refactor: clean up enabling strict mode
  package-lock.json
  package.json
  src/Browser/Browser.ts
  src/Browser/BrowserConfig.ts
  src/CapabilityValidator/CapabilityValidator.ts
  src/Session/Session.ts
  src/Types/types.d.ts
  src/Types/untyped-modules.ts
  src/WebElement/WebElement.ts
  src/app.ts
  src/constants/constants.ts
  src/logger.ts
  src/routes/cookies.ts
  src/routes/elements.ts
  src/routes/index.ts
  src/routes/timeouts.ts
  src/utils/StringUnion.ts
  src/utils/utils.ts
  tsconfig.json
Labels: Type: Refactor/Cleanup

#206 refactor: split session commands into modules
  src/Session/Session.ts
  src/Session/command-handlers/add-cookie.ts
  src/Session/command-handlers/delete-all-cookies.ts
  src/Session/command-handlers/delete-cookie.ts
  src/Session/command-handlers/delete-session.ts
  src/Session/command-handlers/element-clear.ts
  src/Session/command-handlers/element-click.ts
  src/Session/command-handlers/element-enabled.ts
  src/Session/command-handlers/element-is-displayed.ts
  src/Session/command-handlers/element-selected.ts
  src/Session/command-handlers/element-send-keys.ts
  src/Session/command-handlers/execute-script.ts
  src/Session/command-handlers/find-element-from-element.ts
  src/Session/command-handlers/find-element.ts
  src/Session/command-handlers/find-elements-from-element.ts
  src/Session/command-handlers/find-elements.ts
  src/Session/command-handlers/get-active-element.ts
  src/Session/command-handlers/get-all-cookies.ts
  src/Session/command-handlers/get-current-url.ts
  src/Session/command-handlers/get-element-attribute.ts
  src/Session/command-handlers/get-element-tag-name.ts
  src/Session/command-handlers/get-element-text.ts
  src/Session/command-handlers/get-named-cookie.ts
  src/Session/command-handlers/get-page-source.ts
  src/Session/command-handlers/get-timeouts.ts
  src/Session/command-handlers/get-title.ts
  src/Session/command-handlers/index.ts
  src/Session/command-handlers/navigate-to.ts
  src/Session/command-handlers/set-timeouts.ts
  src/Session/command-handlers/switch-to-frame.ts
  src/Session/command-handlers/switch-to-parent-frame.ts
  src/Types/types.d.ts
  src/WebElement/WebElement.ts
  src/utils/utils.ts
Labels: Priority: High, Type: Refactor/Cleanup

#207 feat: Get Element Property Endpoint
  README.md
  src/Session/command-handlers/get-element-property.ts
  src/Session/command-handlers/index.ts
  src/Types/types.d.ts
  src/WebElement/WebElement.ts
  src/constants/constants.ts
  src/routes/elements.ts
  test/jest/get-element-property.test.js
Labels: Priority: Medium, Type: Enhancement

#210 chore: add nvmrc file
  .nvmrc
  README.md
Labels: Type: Enhancement
